
package job;
import javax.swing.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.UnknownHostException;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import com.sun.jndi.ldap.Connection;
import java.sql.SQLException;
import java.sql.*;



public class NewJFrame extends javax.swing.JFrame {
  java.sql.Connection cn = null;
    ResultSet rs = null;
    Statement st;
    int count=0;
    
    
    public NewJFrame() {
        initComponents();
          try
        {
            Class.forName("com.mysql.jdbc.Driver");
      
                cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/job_search","root","");
            st=cn.createStatement();
            JOptionPane.showMessageDialog(null, "Connected");
                   
                   
                   
                    
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, "not connected");
            
       }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Fname = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        Phone_no = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("SIGN UP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(820, 60, 275, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("FName     :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(720, 330, 134, 35);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("LName     :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(720, 380, 134, 35);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Sex           :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(720, 430, 134, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Phone No :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(720, 570, 132, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("(Phone no will be the user_id)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(880, 610, 151, 13);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Password :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(720, 630, 137, 27);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("(Password length should be min 8 characters,it should contain number,alphabet and one special character)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(870, 670, 551, 13);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(900, 790, 230, 50);

        Fname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });
        Fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FnameKeyTyped(evt);
            }
        });
        getContentPane().add(Fname);
        Fname.setBounds(860, 330, 377, 35);

        Lname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameActionPerformed(evt);
            }
        });
        Lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LnameKeyTyped(evt);
            }
        });
        getContentPane().add(Lname);
        Lname.setBounds(860, 380, 377, 35);

        buttonGroup1.add(Male);
        Male.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        getContentPane().add(Male);
        Male.setBounds(870, 430, 113, 37);

        buttonGroup1.add(Female);
        Female.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Female.setText("Female");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        getContentPane().add(Female);
        Female.setBounds(1040, 430, 115, 37);

        Phone_no.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Phone_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phone_noActionPerformed(evt);
            }
        });
        Phone_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Phone_noKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Phone_noKeyTyped(evt);
            }
        });
        getContentPane().add(Phone_no);
        Phone_no.setBounds(860, 570, 373, 35);

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordKeyTyped(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(860, 630, 373, 34);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("Email        :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(720, 520, 137, 27);

        Email.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailKeyReleased(evt);
            }
        });
        getContentPane().add(Email);
        Email.setBounds(860, 520, 377, 34);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(496, 314, 218, 0);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(223, 308, 239, 0);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(335, 342, 191, 0);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1030, 465, 374, 0);
        getContentPane().add(jLabel16);
        jLabel16.setBounds(553, 303, 0, 0);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(342, 357, 198, 0);
        getContentPane().add(jLabel18);
        jLabel18.setBounds(362, 500, 374, 0);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(860, 480, 377, 33);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("DOB          :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(720, 480, 131, 33);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\vmall\\Pictures\\Screenshots\\New folder\\Screenshot (16).png")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 160, 1811, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
         if(Fname.getText().trim().isEmpty() &&
                Phone_no.getText().trim().isEmpty()    && Email.getText().trim().isEmpty()
                && Password.getText().trim().isEmpty()){
            
          jLabel11.setText("Lname is empty");
          jLabel16.setText("Email is empty");
          jLabel17.setText("Phone number is empty");
          jLabel18.setText("Password is empty");
          
                  
         }else if(Fname.getText().trim().isEmpty()){
             jLabel11.setText("Lname is empty");
         }else if(Phone_no.getText().trim().isEmpty()){
           jLabel17.setText("Phone number is empty");  
         }else if(Email.getText().trim().isEmpty()){
             jLabel16.setText("Email is empty");
         }else if(Password.getText().trim().isEmpty()){
             jLabel18.setText("Password is empty");
         }
         
         else{
        
        
         }
        //System.exit(0);
       
       
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/job_search","root","");
            
           String sql = "insert into sign_up values(?,?,?,?,?,?,?)";
           //String sql1 = "insert into login values(?,?)";
          
            PreparedStatement pstmt = conn.prepareStatement(sql);
           // PreparedStatement pstmt1 = conn.prepareStatement(sql1);
             //PreparedStatement pstmt2 = conn.prepareStatement(sql2);
            JOptionPane.showMessageDialog(null, "Connected");
       
            pstmt.setString(1,Fname.getText());
            pstmt.setString(2, Lname.getText());
            
           String sex = null;
            if(Male.isSelected()){
                sex = Male.getText();
            }
            if(Female.isSelected()){
                sex = Female.getText();
            }
        
            
             pstmt.setString(3, sex);
            pstmt.setString(4, Email.getText());
           pstmt.setString(5,Phone_no.getText());
            pstmt.setString(6, Password.getText());
            pstmt.setString(7,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
            pstmt.execute();
            
           // pstmt1.setString(1,Phone_no.getText());
            /// pstmt1.setString(2, Password.getText());
           // pstmt1.execute();
            
        
            
            JOptionPane.showMessageDialog(null,"insertion successfull");
            conn.close(); 
            
            new NewJFrame2().setVisible(true);
        dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameActionPerformed

    private void Phone_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone_noActionPerformed
        // TODO add your handling code here:
        
        //int i = Integer.parseInt(jTextField3.getText());
        //jTextField3.setText(Integer.toString(10));
        
        
    }//GEN-LAST:event_Phone_noActionPerformed
    
    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
        if(count==0){
        Fname.setText("Mr. " + Fname.getText());
        count++;
        }
        
    }//GEN-LAST:event_MaleActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
        if(count==0){
        Fname.setText("Mrs. " + Fname.getText());
         count++;  
        }
    }//GEN-LAST:event_FemaleActionPerformed

    private void Phone_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone_noKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)|| Character.isWhitespace(c) || Character.isISOControl(c))
        {
            
            Phone_no.setEditable(true);
        }else{
            getToolkit().beep();
            Phone_no.setEditable(false);
        }
    }//GEN-LAST:event_Phone_noKeyTyped

    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameActionPerformed

    private void FnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)|| Character.isWhitespace(c) || Character.isISOControl(c))
        {
            
            Fname.setEditable(true);
        }else{
            getToolkit().beep();
            Fname.setEditable(false);
        }
    }//GEN-LAST:event_FnameKeyTyped

    private void LnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LnameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)|| Character.isWhitespace(c) || Character.isISOControl(c))
        {
            
            Fname.setEditable(true);
        }else{
            getToolkit().beep();
            Fname.setEditable(false);
        }
    }//GEN-LAST:event_LnameKeyTyped

    private void FnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnameKeyReleased
        // TODO add your handling code here:
        jLabel11.setText(" ");
    }//GEN-LAST:event_FnameKeyReleased

    private void EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyReleased
        // TODO add your handling code here:
        jLabel16.setText(" ");
    }//GEN-LAST:event_EmailKeyReleased

    private void Phone_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Phone_noKeyReleased
        // TODO add your handling code here:
        jLabel17.setText(" ");
    }//GEN-LAST:event_Phone_noKeyReleased

    private void PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyReleased
        // TODO add your handling code here:
        jLabel18.setText(" ");
        
    }//GEN-LAST:event_PasswordKeyReleased

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PasswordActionPerformed

    private void PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyTyped
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_PasswordKeyTyped

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JRadioButton Male;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Phone_no;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
