/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.UnknownHostException;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import com.sun.jndi.ldap.Connection;
import java.sql.SQLException;
import java.sql.*;
/**
 *
 * @author Vinay
 */
public class NewJFrame2 extends javax.swing.JFrame {
    
 //java.sql.Connection cn = null;
  //ResultSet rs = null;
    //Statement st;
    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
       
        initComponents();
         //try
       // {
        //    Class.forName("com.mysql.jdbc.Driver");
        //Connection cn = new Connection();
        //        cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/job_search","root","");
         //   st=cn.createStatement();
          //  JOptionPane.showMessageDialog(null, "Connected");
                   
                   
                   
                    
       // }
       // catch(Exception e){
        //    JOptionPane.showMessageDialog(null, "not connected");
            
       // }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));
        jDesktopPane1.setForeground(new java.awt.Color(51, 51, 0));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextField1);
        jTextField1.setBounds(560, 320, 335, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("User_id     :");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(270, 310, 208, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 0));
        jLabel3.setText("Password  :");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(260, 410, 220, 60);
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(247, 304, 208, 24);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(690, 580, 207, 77);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jDesktopPane1.add(jPasswordField1);
        jPasswordField1.setBounds(560, 420, 335, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel1.setText("LOG IN");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(510, 150, 260, 67);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton1.setText("LOG IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(360, 580, 260, 77);
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(247, 193, 208, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\vmall\\Pictures\\Screenshots\\Screenshot (26).png")); // NOI18N
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(990, 90, 770, 830);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\vmall\\Pictures\\Screenshots\\New folder\\Screenshot (27).png")); // NOI18N
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(0, 0, 410, 1130);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\vmall\\Pictures\\Screenshots\\New folder\\Screenshot (27).png")); // NOI18N
        jDesktopPane1.add(jLabel8);
        jLabel8.setBounds(410, 0, 430, 1120);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\vmall\\Pictures\\Screenshots\\New folder\\Screenshot (27).png")); // NOI18N
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(840, 0, 560, 1240);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\vmall\\Pictures\\Screenshots\\New folder\\Screenshot (27).png")); // NOI18N
        jDesktopPane1.add(jLabel10);
        jLabel10.setBounds(1273, 0, 430, 1200);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\vmall\\Pictures\\Screenshots\\New folder\\Screenshot (27).png")); // NOI18N
        jDesktopPane1.add(jLabel11);
        jLabel11.setBounds(1703, 0, 450, 1200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1241, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user_id = jTextField1.getText();
        if(jTextField1.getText().trim().isEmpty() &&
                jPasswordField1.getText().trim().isEmpty() )
        {
            jLabel4.setText("user_id is empty");
            jLabel5.setText("Password is empty");
        }
        
        else if(jTextField1.getText().trim().isEmpty())
        {
          jLabel4.setText("user_id is empty");  
        }
        else if(jPasswordField1.getText().trim().isEmpty())
        {
            jLabel5.setText("Password is empty");
        }
        //String s1 =jTextField1.getText();
        //String s = jPasswordField1.getText();
        //OutputStream  out = s1.getOutputStream();
        //PrintWriter w = new PrintWriter(out);
        //w.println(s1);
        //w.flush();
        //System.out.println("Message sent");
        //jTextField1.setText(" ");
        //String sql1 = "INSERT INTO login(User_id,Password)" + "VALUES ( s1 , ' " + s + " ');";
        //try {
          //  st.executeUpdate(sql1);
        //} catch (SQLException ex) {
          //  Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
       // }
        String sql = "Select * from login where User_id = ? and Password = ?  ";
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/job_search","root","");
           PreparedStatement pstmt = conn.prepareStatement(sql);
           pstmt.setString(1, jTextField1.getText());
           pstmt.setString(2, new String(jPasswordField1.getPassword()));
           
           ResultSet rs = pstmt.executeQuery();
           
           if(rs.next())
           {
               JOptionPane.showMessageDialog(null, " Welcome "," Successfull login",JOptionPane.PLAIN_MESSAGE );
                new NewJFrame3(user_id).setVisible(true);
                 dispose();
           }
           else{
               JOptionPane.showMessageDialog(null, " Invalid username/password "," UnSuccessfull login",JOptionPane.ERROR_MESSAGE);
           }
            
           conn.close();
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        }
        
        //String User_id = jTextField1.getText();
       
     
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        jLabel4.setText(" ");
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        // TODO add your handling code here:
        jLabel5.setText(" ");
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        //if(jTextField1.getText().length()==10){
        //    evt.consume();
        //}
        //else{
        //    jLabel4.setText("user_id length should be 10");
       // }
        
            
        
    }//GEN-LAST:event_jTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
